# Generated by Django 4.0.3 on 2022-04-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='宠物名')),
                ('age', models.CharField(max_length=11, verbose_name='年龄')),
                ('gender', models.CharField(max_length=11, verbose_name='性别')),
                ('details', models.CharField(max_length=255, verbose_name='故事')),
                ('category', models.CharField(max_length=22, verbose_name='种类')),
                ('vaccine', models.CharField(max_length=11, verbose_name='免疫')),
                ('repellent', models.CharField(max_length=11, verbose_name='驱虫')),
                ('sterilization', models.CharField(max_length=22, verbose_name='绝育')),
                ('imgurl', models.CharField(max_length=255, verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=22, verbose_name='标题')),
                ('details', models.CharField(max_length=255, verbose_name='公告详细')),
                ('n_time', models.CharField(max_length=22, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='question_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='题干')),
                ('answer_A', models.CharField(max_length=255, verbose_name='选项A')),
                ('answer_B', models.CharField(max_length=255, verbose_name='选项B')),
                ('answer_C', models.CharField(max_length=255, verbose_name='选项C')),
                ('answer_D', models.CharField(max_length=255, verbose_name='选项D')),
                ('current_ans', models.CharField(max_length=255, verbose_name='正确答案')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True, verbose_name='收支明细')),
                ('money', models.SmallIntegerField(verbose_name='金额')),
                ('status', models.CharField(max_length=11, verbose_name='状态')),
                ('source', models.CharField(max_length=255, verbose_name='来源')),
                ('time', models.CharField(max_length=255, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, null=True, verbose_name='用户名')),
                ('userphone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(max_length=11, null=True, verbose_name='性别')),
                ('password', models.CharField(max_length=11, null=True, verbose_name='密码')),
                ('email', models.CharField(max_length=22, null=True, verbose_name='邮箱')),
                ('userscore', models.SmallIntegerField(default='10', verbose_name='积分')),
                ('role', models.CharField(default='1', max_length=11, verbose_name='用户权限')),
                ('avatarUrl', models.CharField(default='chengdu.myqcloud.com/animalimage/dogs/dog38.jpg', max_length=255, verbose_name='用户头像')),
                ('registTime', models.CharField(max_length=255, verbose_name='注册时间')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户TOKEN')),
                ('openid', models.CharField(default='', max_length=255, verbose_name='微信用户id')),
                ('address', models.CharField(default='', max_length=255, null=True, verbose_name='收货地址')),
            ],
        ),
        migrations.CreateModel(
            name='usersign_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='usersign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_days', models.SmallIntegerField(verbose_name='累计签到天数')),
                ('last_sign', models.DateTimeField(auto_now_add=True, verbose_name='最后一次签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='supportinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=22, verbose_name='捐赠多少')),
                ('uid', models.CharField(max_length=255, verbose_name='云养号')),
                ('status', models.CharField(default='1', max_length=11, verbose_name='状态')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.animalinfo', verbose_name='动物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='sendanimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='宠物名')),
                ('age', models.CharField(max_length=11, verbose_name='年龄')),
                ('gender', models.CharField(max_length=11, verbose_name='性别')),
                ('details', models.CharField(max_length=255, verbose_name='故事')),
                ('category', models.CharField(max_length=11, verbose_name='种类')),
                ('vaccine', models.CharField(max_length=11, verbose_name='免疫')),
                ('repellent', models.CharField(max_length=11, verbose_name='驱虫')),
                ('sterilization', models.CharField(max_length=22, verbose_name='绝育')),
                ('imgurl', models.CharField(max_length=255, verbose_name='图片')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('status', models.SmallIntegerField(choices=[(1, '待审核'), (2, '审核成功')], default='1', verbose_name='状态')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='seekanimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalname', models.CharField(max_length=11, verbose_name='宠物名')),
                ('age', models.CharField(max_length=11, verbose_name='年龄')),
                ('gender', models.CharField(max_length=11, verbose_name='性别')),
                ('dogdetails', models.CharField(max_length=255, verbose_name='故事')),
                ('category', models.CharField(max_length=22, verbose_name='种类')),
                ('time', models.CharField(max_length=22, verbose_name='丢失时间')),
                ('adress', models.CharField(max_length=255, verbose_name='丢失地点')),
                ('imgurl', models.CharField(max_length=255, verbose_name='宠物图片')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('depth', models.PositiveIntegerField(default=1, verbose_name='评论级数')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='赞数')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.animalinfo', verbose_name='狗')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replys', to='api.commentrecord', verbose_name='回复')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roots', to='api.commentrecord', verbose_name='根评论')),
                ('send', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sendanimal', verbose_name='送养')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='评论者')),
            ],
        ),
        migrations.CreateModel(
            name='adoptUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, verbose_name='用户名')),
                ('age', models.CharField(max_length=11, verbose_name='年龄')),
                ('work', models.CharField(max_length=11, verbose_name='工作状态')),
                ('experience', models.CharField(max_length=11, verbose_name='养宠经验')),
                ('married', models.CharField(max_length=11, verbose_name='婚姻状况')),
                ('salary', models.CharField(max_length=11, verbose_name='工资')),
                ('address', models.CharField(max_length=11, verbose_name='所在地')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('adoptdetail', models.CharField(max_length=255, verbose_name='领养说明')),
                ('status', models.SmallIntegerField(choices=[(1, '未领养'), (2, '同意领养')], verbose_name='收养状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.animalinfo', verbose_name='动物ID')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
    ]
