# Generated by Django 4.0.3 on 2022-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adoptuserinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersign_log',
            name='sign_time',
        ),
        migrations.AddField(
            model_name='usersign_log',
            name='sign_day',
            field=models.SmallIntegerField(default=2, verbose_name='签到时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersign_log',
            name='sign_month',
            field=models.SmallIntegerField(default=4, verbose_name='签到时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersign_log',
            name='sign_year',
            field=models.SmallIntegerField(default=10, verbose_name='签到时间'),
            preserve_default=False,
        ),
    ]
