# Generated by Django 4.0.3 on 2022-04-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usersign_log_sign_time_usersign_log_sign_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersign_log',
        ),
    ]
