# Generated by Django 4.0.3 on 2022-04-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_usersign_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersign_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_year', models.SmallIntegerField(verbose_name='签到时间')),
                ('sign_month', models.SmallIntegerField(verbose_name='签到时间')),
                ('sign_day', models.SmallIntegerField(verbose_name='签到时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.userinfo', verbose_name='用户ID')),
            ],
        ),
    ]
